### ISSUE TITLE
Great project outline! - the tracker link is missing

### ISSUE THREAD

**Issue by cherylschaefer** [EyeLikeFire/liftoff-assignments#1]
https://github.com/EyeLikeFire/liftoff-assignments/blob/master/P2-Project_Outline/README.md

Love your overview!
Good job on your feature descriptions too. You might want to split "leave comments/reactions" from "view art" (optional suggestion). Consider some privacy issues, can specific users be blocked from viewing or commenting? or maybe some piece of art is private and only a specific list of users should be allowed to see it?
I like the order of your epics too -- most people put user login first, but it can be more rewarding to put that off and do the main part first.

**Comment by EyeLikeFire** [comment]
Great feedback!
Here is the link to the tracker:

https://www.pivotaltracker.com/n/projects/2343805

Note: I changed the privacy settings within Pivotal to make the link public.
